background_opacity      0.8
cursor_trail            10

background #212121
foreground #E6E6E6
selection_background #1A73E8
selection_foreground #FFFFFF
url_color #1A73E8
cursor #E6E6E6
cursor_text_color #212121

enable_audio_bell no

# Tabs
active_tab_background #1A73E8
active_tab_foreground #FFFFFF
inactive_tab_background #2A2A2A
inactive_tab_foreground #969696

# Windows
active_border_color #1A73E8
inactive_border_color #2A2A2A

# normal
color0 #212121
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #1A73E8
color5 #bb9af7
color6 #7dcfff
color7 #E6E6E6

# bright
color8  #3D3D3D
color9  #ff899d
color10 #9fe044
color11 #faba4a
color12 #4a90e8
color13 #c7a9ff
color14 #a4daff
color15 #FFFFFF

# extended colors
color16 #ff9e64
color17 #db4b4b
