#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output  eDP-1 --mode 1366x768 --rate 60.00 --pos 0x440 --output HDMI-1 --primary --mode 1920x1080 --rate 120.00 --pos 1366x0 --rotate normal
bspc monitor eDP-1 -d 1
bspc monitor HDMI-1 -d 2
bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color "#2A2A2A"
bspc config focused_border_color "#1A73E8"

bspc desktop -f '^2'

bspc rule -a Brave-browser desktop='^2' follow=on state=tiled
bspc rule -a HeliumBrowser desktop='^1' follow=on state=tiled
bspc rule -a Min desktop='^2' follow=on state=tiled
bspc rule -a firefox desktop='^1' follow=on state=tiled
bspc rule -a kitty desktop='^1' follow=on state=tiled
bspc rule -a Code desktop='^2' follow=on state=tiled
bspc rule -a Sublime_text desktop='^2' follow=on state=tiled
bspc rule -a anytype desktop='^2' follow=on state=tiled
bspc rule -a Capacities desktop='^2' follow=on state=tiled
bspc rule -a obsidian desktop='^2' follow=on state=tiled
bspc rule -a Thunar desktop='^1' follow=on state=tiled

feh --bg-scale /home/oguzhan/Pictures/Wallpaper/mirror.jpeg &
polybar main &
polybar external &
picom --config ~/.config/picom/picom.conf &
~/.config/bspwm/autostart.sh
xset s off -dpms s noblank &
